# baseURL
baseURL = 'https://rengchi.github.io/'
# ä¸­æ–‡
languageCode = 'zh-cn'
# æ ‡é¢˜
title = 'ä»è¿Ÿ'
# ä¸»é¢˜
theme = "PaperMod"

[params]
env = 'production'
defaultTheme = "auto"                                    # ä¸»é¢˜æ¨¡å¼ï¼šautoï¼ˆè‡ªåŠ¨ï¼‰ã€lightï¼ˆäº®è‰²ï¼‰ã€darkï¼ˆæš—è‰²ï¼‰
ShowSearch = true                                        # æ˜¾ç¤ºæœç´¢
author = "ä»è¿Ÿ"                                            # ä½œè€…
description = "è®©æ— å¤„ä¸åœ¨çš„æŠ€æœ¯ï¼Œæˆä¸ºäººäººå¹³ç­‰çš„æƒåˆ©"                       # æè¿°
homeInfoParams = { Title = "ä»è¿Ÿ", Content = "çŸ¥ä¹‹è¡Œä¹‹ï¼Œæ— è´Ÿä»Šæ—¥" } # / é¡µé¢ä¿¡æ¯
DateFormat = "2006å¹´01æœˆ02æ—¥"                               # æ—¥æœŸæ ¼å¼

[[params.socialIcons]]
name = "github"
url = "https://github.com/rengchi"

[params.profileMode]
enabled = true
title = 'ä»è¿Ÿ'
subtitle = 'çŸ¥ä¹‹è¡Œä¹‹ï¼Œæ— è´Ÿä»Šæ—¥'
imageUrl = 'img/logo.png'
imageTitle = 'éœ'
imageWidth = 126
imageHeight = 126
[[params.profileMode.buttons]]
name = "ğŸ“ æ–‡ç« "
url = "/posts"

[minify]
disableXML = true

[outputs]
home = ["HTML", "RSS", "JSON"] # éœ€è¦ç”Ÿæˆ JSON æ–‡ä»¶

[menu]
[[menu.main]]
name = "ğŸŒ å½’æ¡£"
url = "/archives/"
weight = 1
[[menu.main]]
name = "ğŸ”æœç´¢"
url = "/search/"
weight = 2
[[menu.main]]
name = "ğŸ“Œæ ‡ç­¾"
url = "/tags/"
weight = 3
